# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BTCoreExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for BTCoreExample
  pod 'RTRootNavigationController'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'BTLoading'
  pod 'BTHelp','~> 0.1.4'

end
